### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by slawiko** [NNikiforov/Training-practice#2]
@NNikiforov 

Верстка аккуратная. Круто, что разбивали css файлы 👍 

Пока вопросов нет, но жду ваших сегодняшних изменений.

**Comment by NNikiforov** [comment]
Mission has been completed. + добавил подсказки для тегов.

**Comment by slawiko** [comment]
CSS:
- очень часто используете `float`, даже там, где это не нужно. Почитайте: https://habrahabr.ru/post/142486/ , вам будет интересно. И вообще в целом почитайте что-нибудь по запросу `CSS поток`.
- когда вы делаете `float`, `display: inline-block` перестает работать.

Стало лучше. Подкупили подсказки для тегов, молодцы.
В целом хотелось бы большей аккуратности. И вдумчивости. Я понимаю, что времени мало, но уделяйте какую-то его часть на чуть более глубокое изучение. Статьи на хабре, например - прекрасный вариант.
