### ISSUE TITLE
Task 4

### ISSUE THREAD

**Issue by batist73** [NNikiforov/Training-practice#3]
@NNikiforov 

**Модуль:**
* Скрипт необходимо было встроить в ваш html код, чтобы он исполнялся на стороне браузера и логировал в консоль Dev Tools.

**getPhotoPosts:**
* Непонятная проверка ``filterConfig.date !== 'Invalid Date'``. Следует использовать instanceof Date.

**validatePhotoPost:**
* typeof для объекта даты выдаст "object".

**addPhotoPost:**
* А выражение ``photoPosts.length + 1 === photoPosts.push(photoPost)`` может вернуть false?

**editPhotoPost:**
* При выполнении метода вы удаляете и добавляете пост, из-за чего он может изменить своё расположение в массиве. Можно просто использовать стандартный метод splice(), чтобы заменять пост в массиве "на месте".

**Comment by NNikiforov** [comment]
Здравствуйте.
По поводу модуля не совсем понятно. Я не туда вставил логирование? Но ведь оно отображается в консоле Dev Tools, да и sсript. js вроде подключён.
![image](https://user-images.githubusercontent.com/22747349/37485217-eb59f24c-289b-11e8-9da8-9da3bc239ab1.png)

Проверку даты везде исправил.

Странное выражение тоже исправил. Думал проверить добавление в массив, почитал и понял, что оно правильно работает в любом случае. Перестарался :)

По поводу created at. Не уверен, что стоит хранить массив в отсортированном виде, т.к. после изменения поста реальный результат сортировки может оказаться совершенно другим. Например при сортировке по хештегу. Если пользователь решит изменить именно хештег, то вряд ли результат сортировки останется прежним. Это свидетельствует о том, что бояться иного расположения элементов в массиве не стоит. По поводу моего "не использования splice()": Я предпринял такой способ из-за особенности моего validate. Он проверяет на уникальность ID, а т.к. мы меняем пост, данный id уже существует. Вышел из этой проблемы я следующим образом: удаляю элемент из массива, проверяю "старым" validate и добавляю старый или новый элемент в зависимости от результата. Если использовать splice(), мне придётся сделать отдельную реализацию validate для функции edit. В общем не уверен, что стоит это менять. Что вы скажете по этому поводу?
