### ISSUE TITLE
Task 7

### ISSUE THREAD

**Issue by batist73** [NNikiforov/Training-practice#4]
@NNikiforov 

**Задание:**
* В задании подразумевалось, что на 10 баллов необходимо реализовать отдачу статики как с помощью Express, так и средствами одного http модуля, то есть попробовать и то и то. Поэтому добавьте обработку статики на Express (благо, это не долго), внеся Express в dependencies вашего проекта и воспользовавшись стандартным мидлваром express.static. Можете поместить уже написанный с помощью http сервер в файл app-http.js, а в app.js реализовать сервер с Express, так как в дальнейшем вы будете работать именно с ним. Баллы за эту доработку снижать не будем. Просто для полноты картины стоит добавить Express статику.

**package.json:**
* А почему package.json находится в директории public? package.json следует размещать в корне вашего приложения. К тому же, он скорее относится к вашему серверу, то есть в public ему точно не место.

**Пути:**
* Сейчас, чтобы получить клиент, необходимо обратиться по адресу localhost:3000/public/index.html, что не совсем удобно. Обычно клиент получают из корня сервера, то есть по адресу localhost:3000 в вашем случае.

**Comment by NNikiforov** [comment]
Готово

**Comment by batist73** [comment]
@NNikiforov 

👍
